### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by leshokunin** [GetEpona/Epona-js#15]
## Introduction
Serving Epona right now requires:
- installing NPM
- Textile
- using the command line
Also, Epona is only usable inside the browser, after serving it locally.

It would be better to have an executable app, that:
1. Has an installer for all the moving parts (web server, Textile node, Epona, Electron)
2. Can run a program and show Epona in a web view (rather than open in the browser)

## Using ElectronJS
Electron is a great means to display HTML/JS in a simple native executable. This shouldn't prevent users from opening the page in their browser if they want, it's just for convenience.
All packaging methods must have the ability to start/connect to a Textile instance.

[Electron | Build cross platform desktop apps with JavaScript, HTML, and CSS.](https://electronjs.org/)

### Advantages:
- Easy to program
- Simple deployment
- Native access
- Cross platform

### Disadvantages:
- Large executable file size and overhead (we can live with that)
- Redundantly pack dependencies (same)
- Inefficient, uses large amounts of RAM or CPU for complex operations (fine for desktop for now)
- Full browser instance with native access (Potential security issue).

### Building
1. git clone (Insert repo here); cd (insert repo here)
2. Install Electron builder if not installed `npm install electron-builder -g`
3. Compile for all operating platforms `electron-builder -mvl`
4. Publish dist/ to github and IPFS.

### Advantages:
- Lightweight
- Cross-platform
- Full native access

### Disadvantages:
- Requires Java to be installed, could install Java when Epona is installing (if not already installed)
- Some potential extra setup/deployment operations.

### Building
1. git clone  (Insert repo here); cd (insert repo here)
2. Compile with maven `mvn clean compile assembly:single`
3. Publish target/ to github and IPFS.

## Release signing
All releases should be signed and checksummed. This is done via GPG.
Not finalized, do not use this process until further revision. Script will be made for automating the process
In directory of release:
1. `gpg -s -a * -u (insert release user ID)` 
2. Releases for each OS/arch should be separate files, similar to the way IPFS distributes its own executables. Ex [`https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_darwin-amd64.tar.gz`](https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_darwin-amd64.tar.gz)

**Comment by eponabuilder** [comment]
@NatoBoram this was the initial spec made by @dtubenetwork for the auto builder

**Comment by NatoBoram** [comment]
Oh. Right now there's no signing, but everything else is done.
