### ISSUE TITLE
files API: 404 not found 

### ISSUE THREAD

**Issue by dtubenetwork** [GetEpona/Epona-js#17]
Receiving a 404 not found under network tab. 
URL: http://127.0.0.1:40600/api/v0/files
Notable request headers: X-Textile-Opts: thread=%5Bobject%20Object%5D,offset=,limit=5
*more details sent on discord*

**Comment by leshokunin** [comment]
I think this was fixed in the new version, right? @dtubenetwork cc @andrewxhill
